### ISSUE TITLE
[BUG] Multi tools qui "casse pas" l'herbe 

### ISSUE THREAD

**Issue by Otachi0** [RivrsMc/EvoluCraft-Issues#100]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

Otachii

### Pseudo discord

Otachi

### Que s'est-il passé ?

lorsqu'on utilise la multi tools en passant de la roche (par exemple) à des blocs d'herbes la multi tools ne casse plus instant (c'est pas très clair mais j'ai fait une petite vidéo)

### Étapes à suivre pour reproduire le bug

1 prendre une multi tools 2 essayer de casser des blocs d'herbe 

### Qu'aurait-il dû arriver ?

casser les blocs d'herbe instant 

### Date et heure de la production du bug

22h38 19/07

### Serveur

Construction02 (Jaya)

### Screen / vidéo

https://streamable.com/q5uocz

**Comment by Volrod678** [comment]
Fix
