### ISSUE TITLE
[SUGGESTION]Faute d'orthographe

### ISSUE THREAD

**Issue by TheKalyti** [RivrsMc/EvoluCraft-Issues#210]
### Pseudo en jeu

Kalyti

### Suggestion

Correction de la faute d'orthographe présente sur le Bandana du Moussaillon

Nom en jeu : Bandana du Mousaillon

Nom correct : Bandana du Moussaillon

Merci d'avance :)

### Information supplémentaire

![2023-08-06_22 33 39](https://github.com/RivrsMc/EvoluCraft-Issue/assets/138994867/43a17e37-461b-43e2-869f-872d55eee645)

**Comment by Volrod678** [comment]
Fix
