### ISSUE TITLE
[SUGGESTION] kit premium

### ISSUE THREAD

**Issue by CorieTutTut** [RivrsMc/EvoluCraft-Issues#215]
### Pseudo en jeu

Corie__

### Suggestion

Ne pas pouvoir récupérer son kit premium si nous n'avons pas 6 slots de disponible 

### Décrivez la solution que vous souhaitez

![image](https://github.com/RivrsMc/EvoluCraft-Issue/assets/137453358/00ac7ae1-307f-418c-8534-b87419feb401)

Recevoir ce message-là

**Comment by Volrod678** [comment]
Fix
