### ISSUE TITLE
[SUGGESTION] Kit ultime dans la box premium

### ISSUE THREAD

**Issue by CorieTutTut** [RivrsMc/EvoluCraft-Issues#217]
### Pseudo en jeu

Corie__

### Suggestion

Lorsqu'un joueur reçoit un kit ultime dans sa box premium, il faut avoir 20 slots pour recevoir le kit. Or, il se peut que le joueur n'ait pas les slots nécessaires pour le recevoir 

### Décrivez la solution que vous souhaitez

Au lieu de recevoir le kit, peut-être recevoir un bout de papier et en mode, le joueur clique droit dessus et reçoit le kit et s'il n'a pas assez de place dans son inventaire, ça refuse de lui donner le kit jusqu'à ce qu'il ait 20 slots de disponible

Si le joueur n'a pas assez de slot, ça lui envoie ce message là :
![image](https://github.com/RivrsMc/EvoluCraft-Issue/assets/137453358/1a33f205-41e5-449f-b20c-a67f8be34177)

**Comment by Volrod678** [comment]
Fix
