### ISSUE TITLE
[SUGGESTION] Recevoir les voteparty pendant un donjon

### ISSUE THREAD

**Issue by CardiLyce** [RivrsMc/EvoluCraft-Issues#233]
### Pseudo en jeu

CardiLyce

### Suggestion

Des joueurs ne recoivent pas les clefs de voteparty quand ils sont en donjon, c'est un peu dommage

### Décrivez la solution que vous souhaitez

Rajouter le plugin pour recevoir les clefs votes (ou les stocker dans le "Récupérer" du /vote, ou mettre carrément a jour la méthode de recevoir les clefs)

**Comment by Volrod678** [comment]
Fix
