### ISSUE TITLE
[BUG]statue commun à la place de légendaire

### ISSUE THREAD

**Issue by maxjerbis** [RivrsMc/EvoluCraft-Issues#266]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

maxjerbis

### Pseudo discord

maxjerbis

### Que s'est-il passé ?

dans la tailleuse de pierre quand l'on fait des statuts légendaire, quand elles on fini c'est écrit commun au lieu de légendaire 

### Étapes à suivre pour reproduire le bug

faire des statut légendaires 

### Qu'aurait-il dû arriver ?

que se soit écrit légendaire 

### Date et heure de la production du bug

Le 13/08:23 à 14h27

### Serveur

None

### Screen / vidéo

![image](https://github.com/RivrsMc/EvoluCraft-Issue/assets/137526378/82c2f410-3a6a-4acf-b293-d99a5edecb26)

### Information supplémentaire

X

**Comment by Alexis700** [comment]
Corrigé
