### ISSUE TITLE
[BUG] /repair all bug (/repair même soucis)

### ISSUE THREAD

**Issue by CardiLyce** [RivrsMc/EvoluCraft-Issues#269]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

CardiLyce

### Pseudo discord

CardiLyce

### Que s'est-il passé ?

Quand un joueur fait /repair all ou /repair et qui sort "_vous pouvez utiliser dans 1h..." le cooldown se reset directement à 12h sans avoir réparé les items

### Étapes à suivre pour reproduire le bug

1. /repairall en cooldown ou /repair
2. Utiliser la commande pendant le cooldown (juste check cb de temps pr la prochaine utilisation)
3. La commande remet le cooldown a 12h sans rien réparer

### Qu'aurait-il dû arriver ?

Ne pas avoir ce reset

### Date et heure de la production du bug

14h30

### Serveur

None

### Screen / vidéo

Aucun

### Information supplémentaire

il y a sûrement pas que le cooldown qui pose soucis

**Comment by ArDiDEx** [comment]
Hello ça sera réglé au prochain restart
Merci du report
