### ISSUE TITLE
[BUG] Hache Ultime qui ne ramasse pas les objets automatiquement

### ISSUE THREAD

**Issue by CardiLyce** [RivrsMc/EvoluCraft-Issues#276]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

CardiLyce

### Pseudo discord

CardiLyce

### Que s'est-il passé ?

La hache ultime ramasse uniquement les blocks cassés, mais pas celui qu'on casse (donc si on casse un escalier en bois, il ne va pas directement dans l'inventaire)

### Étapes à suivre pour reproduire le bug

1. Hache ultime
2. casser un escalier, dalles, etc...
3. Voir que ça drop au sol et non dans l'inv

### Qu'aurait-il dû arriver ?

que ça aille dans l'inv

### Date et heure de la production du bug

y a 2-3jours

### Serveur

None

### Screen / vidéo

On voit bien que la première buche se drop, mais celle du dessus va dans la hot bar

https://github.com/RivrsMc/EvoluCraft-Issue/assets/137453062/1b71e55f-6ab2-4b4d-a18a-ff6d711b6be3

**Comment by ArDiDEx** [comment]
Hello! ça sera fix dans les prochains jours
Merci du report
