### ISSUE TITLE
[BUG] Mort de chute en faisant /cwr rtp

### ISSUE THREAD

**Issue by CorieTutTut** [RivrsMc/EvoluCraft-Issues#280]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

Corie__

### Pseudo discord

tuttut_corie

### Que s'est-il passé ?

Lorsque l'on se tp aléatoirement en ressources, il se peut qu'on soit TP en l'air, puis retp au sol mais on meurt tout de même de chute

### Étapes à suivre pour reproduire le bug

1- Aller en ressource
2- se faire tp (/cwr rtp)
3- se faire tp une première fois en l'air
4- se faire tp une deuxième fois au sol
5- mourir + perdre son stuff

### Qu'aurait-il dû arriver ?

1- Aller en ressource
2- se faire tp (/cwr rtp)
3- pouvoir vagabonder comme bon nous semble

### Date et heure de la production du bug

idk

### Serveur

Ressource01

### Screen / vidéo

https://github.com/RivrsMc/EvoluCraft-Issue/assets/137453358/a614fce6-51d4-41d1-b706-cccd8916c17a

### Information supplémentaire

Suggestion : mettre un effet (comme résistance) pendant quelques minutes en effectuant la commande /cwr rtp ou bien en allant juste en ressource pour éviter de mourir de chute

**Comment by Asherate** [comment]
Toujours d'actualité ?

**Comment by CorieTutTut** [comment]
![image](https://github.com/RivrsMc/EvoluCraft-Issues/assets/137453358/7ef45155-2b94-461d-a123-3d0ffc0f7e86)
Yop, apparemment ça le refait :(
