### ISSUE TITLE
Pioches en 3*3 ne fonctionnent pas dans l'end [BUG] 

### ISSUE THREAD

**Issue by Gaia-32** [RivrsMc/EvoluCraft-Issues#282]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

Gaia_32

### Pseudo discord

Gaia_32

### Que s'est-il passé ?

Report par blackfield, il lui était impossible de miner dans l'end (End1) avec des pioches en 3*3

J'ai testé également, et en effet, il m'était impossible de miner avec le marteau en rubis, je minais par 1 

### Qu'aurait-il dû arriver ?

Normalement, le marteau rubis mine en 3*3

### Serveur

Ressource01

**Comment by ArDiDEx** [comment]
Hello!
C'est réglé 
Merci du report
