### ISSUE TITLE
[BUG] timer récupérer quête journalière

### ISSUE THREAD

**Issue by CorieTutTut** [RivrsMc/EvoluCraft-Issues#287]
### Confirmation

- [x] J'ai bien vérifié si le bug a déjà été report
- [x] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

Corie__

### Pseudo discord

tuttut_corie

### Que s'est-il passé ?

Le timer de la "nouvelle quête disponible dans:" n'est pas dispo, il n'y a pas de tiemr 

### Étapes à suivre pour reproduire le bug

1- Récupérer sa quête journalière utilme
2- voir qu'on ne sait pas dans combien de temps elle est disponible 

### Qu'aurait-il dû arriver ?

voir le timer

### Date et heure de la production du bug

xx.xx.xxxx xx:xx

### Serveur

None

### Screen / vidéo

![image](https://github.com/RivrsMc/EvoluCraft-Issue/assets/137453358/39381e1f-2240-46ae-a764-fa6edb15160c)

**Comment by Volrod678** [comment]
Fix
