### ISSUE TITLE
[BUG] Bug vanish/spectateur non réglé

### ISSUE THREAD

**Issue by CardiLyce** [RivrsMc/EvoluCraft-Issues#290]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

CardiLyce

### Pseudo discord

CardiLyce

### Que s'est-il passé ?

https://github.com/RivrsMc/EvoluCraft-Issue/issues/284 Après plusieurs tests, on a toujours le soucis
Quand on se met en vanish + spectateur et qu'on repasse en survie, on devient réellement invisible

Juste être en spectateur peut vraiment nous rendre invisible uniquement visuel, mais Être présent dans le tab

### Étapes à suivre pour reproduire le bug

X

### Qu'aurait-il dû arriver ?

Être visible

### Date et heure de la production du bug

05h00 

### Serveur

None

### Screen / vidéo

Comme d'habitude les mêmes soucis que le https://github.com/RivrsMc/EvoluCraft-Issue/issues/284

**Comment by Volrod678** [comment]
C'est un bug de minecraft avec l'invi, mais tu peut simplement faire 2x /vanish pour te fix de ton invi
