### ISSUE TITLE
[BUG] Palier 18, jours de premium pas cumulable 

### ISSUE THREAD

**Issue by CorieTutTut** [RivrsMc/EvoluCraft-Issues#300]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

Corie__

### Pseudo discord

tuttut_corie

### Que s'est-il passé ?

Un joueur a reçu les récompenses de son palier 18 sauf qu'il a reçu 2 jours au lieu de 3 (1+2) 

Palier 18 : 
Récompense normale : 1 jour de premium
Récompense premium : 2 jours de premium 

Les 2 récompenses ne se sont pas cumulées

### Étapes à suivre pour reproduire le bug

1- atteindre le palier 18
2- avoir 2 joues de premium au lieu de 3

### Qu'aurait-il dû arriver ?

1- atteindre le palier 18
2- avoir 3 jours de premium

### Date et heure de la production du bug

xx xx xxxxxxxxx

### Serveur

None

**Comment by Volrod678** [comment]
Fix
