### ISSUE TITLE
[BUG] Mauvais tag précisé en finissant la collection insecte

### ISSUE THREAD

**Issue by CardiLyce** [RivrsMc/EvoluCraft-Issues#302]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

CardiLyce

### Pseudo discord

CardiLyce

### Que s'est-il passé ?

Quand on finit la collection des insectes, il est indiqué dans le chat qu'on obtient le tag "Rubis" , alors que nous obtenons le tag "Antman"

### Étapes à suivre pour reproduire le bug

1. Finir la collection des insectes
2. Voir dans le chat que c'est indiqué qu'on reçoit le tag Rubis
3. Voir dans le /tags que c'est antman et non rubis

### Qu'aurait-il dû arriver ?

Avoir marqué "Antman" (et non Rubis)

### Date et heure de la production du bug

23h00

### Serveur

Spawn

### Screen / vidéo

![image](https://github.com/RivrsMc/EvoluCraft-Issue/assets/137453062/61aac91d-bc90-44d1-a0c9-25456ceae5fb)

**Comment by Volrod678** [comment]
Fix
