### ISSUE TITLE
[BUG]hache premium d'aout 

### ISSUE THREAD

**Issue by maxjerbis** [RivrsMc/EvoluCraft-Issues#308]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

maxjerbis

### Pseudo discord

maxjerbis

### Que s'est-il passé ?

La hache premium du mois d'aout casse les pancarte privé des autres joueurs 

### Étapes à suivre pour reproduire le bug

Prendre une hache premium du mois d'aout et casser les panneaux privates des autres 

### Qu'aurait-il dû arriver ?

Que les panneaux ne se casse pas

### Date et heure de la production du bug

15/10/2023 18h51

### Serveur

Spawn

### Screen / vidéo

X

### Information supplémentaire

X

**Comment by Volrod678** [comment]
Fix
