### ISSUE TITLE
[BUG] pets qui n'apparait pas

### ISSUE THREAD

**Issue by CardiLyce** [RivrsMc/EvoluCraft-Issues#310]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

CardiLyce

### Pseudo discord

CardiLyce

### Que s'est-il passé ?

Tout les nouveaux pets halloween ne veulent pas apparaître dans le monde quand on veut les faire apparaitre (ducoup on peut pasl es levelup)

### Étapes à suivre pour reproduire le bug

1. Avoir un pet halloween (nimbus, citrouille...)
2. essayer de le faire apparaitre
3. rien

### Qu'aurait-il dû arriver ?

Les faire apparaitre

### Date et heure de la production du bug

19h45

### Serveur

Spawn

### Screen / vidéo

![image](https://github.com/RivrsMc/EvoluCraft-Issues/assets/137453062/4049972c-b3b7-4575-a729-616bfec6f90b)

**Comment by Volrod678** [comment]
Fix
