### ISSUE TITLE
[BUG] Dura infini sur l'arc Halloween

### ISSUE THREAD

**Issue by CorieTutTut** [RivrsMc/EvoluCraft-Issues#317]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

Corie__

### Pseudo discord

tuttut_corie

### Que s'est-il passé ?

L'arc Halloween ne descends pas en durabilité

### Étapes à suivre pour reproduire le bug

1- avoir un arc halloween
2- l'utiliser
3- la dura ne descends pas

### Qu'aurait-il dû arriver ?

1- avoir un arc halloween
2- l'utiliser
3- la dura descends 

### Date et heure de la production du bug

16/10/2023 - 23h50

### Serveur

Spawn

### Screen / vidéo

https://streamable.com/0ro0iv

**Comment by ArDiDEx** [comment]
Hello!
Un patch pour ça arrivera dans les prochains jours
Merci du report
