### ISSUE TITLE
[BUG] ON A PAS LES EMOTES AU .E ??!?!

### ISSUE THREAD

**Issue by CardiLyce** [RivrsMc/EvoluCraft-Issues#319]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

CardiLyce

### Pseudo discord

CardiLyce

### Que s'est-il passé ?

Surpristi ! Arnaque ! Stupéfait ! On a pas accès aux nouvelles emotes ?!

### Étapes à suivre pour reproduire le bug

1. /e
2. essayer les emojis
3. pas accès

### Qu'aurait-il dû arriver ?

avoir accès au moins non ? :((

### Date et heure de la production du bug

20h00

### Serveur

Spawn

### Screen / vidéo

![image](https://github.com/RivrsMc/EvoluCraft-Issues/assets/137453062/aceba9a4-9642-495c-be48-0005cfc5cf9a)

### Information supplémentaire

dans tout les mondes

**Comment by Volrod678** [comment]
Fix
