### ISSUE TITLE
[BUG]quete épique spam chat

### ISSUE THREAD

**Issue by maxjerbis** [RivrsMc/EvoluCraft-Issues#320]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

maxjerbis

### Pseudo discord

maxjerbis

### Que s'est-il passé ?

Quand l'on fini une quête épique on reçoit plusieurs fois la notif dans le chat que nous avons fini

### Étapes à suivre pour reproduire le bug

Finir une quête épique

### Qu'aurait-il dû arriver ?

Qu'il y a qu'un seul message

### Date et heure de la production du bug

20/10/2023 18h

### Serveur

Spawn

### Screen / vidéo

![image](https://github.com/RivrsMc/EvoluCraft-Issues/assets/137526378/90f1086b-c6a3-4d47-a8d5-f54c8156f521)

### Information supplémentaire

X

**Comment by Volrod678** [comment]
Nous n'avons pas réussi à reproduire le bug pour le moment, si possible d'avoir plus d'information sur le bug

**Comment by maxjerbis** [comment]
Hello je referais des tests :)

**Comment by maxjerbis** [comment]
Jamais réussi à refaire le bug @Volrod678 :/

**Comment by Alexis700** [comment]
Corrigé
