### ISSUE TITLE
[BUG] ressources affichage point summer au lieu de point halloween 

### ISSUE THREAD

**Issue by CorieTutTut** [RivrsMc/EvoluCraft-Issues#323]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

Corie__

### Pseudo discord

tuttut_corie

### Que s'est-il passé ?

On a encore l'affichage des points pirates en ressources 

### Étapes à suivre pour reproduire le bug

1- aller en ressource
2- voir nos points summer

### Qu'aurait-il dû arriver ?

1- aller en ressource
2- voir les points halloween

### Date et heure de la production du bug

18h58 22/10

### Serveur

Spawn

### Screen / vidéo

![image](https://github.com/RivrsMc/EvoluCraft-Issues/assets/137453358/58623ad2-17fa-4edb-8662-c562d1cc00cf)

### Information supplémentaire

Ressources #1 et #2

**Comment by Volrod678** [comment]
Fix
