### ISSUE TITLE
[BUG]hortogaphe votes 

### ISSUE THREAD

**Issue by maxjerbis** [RivrsMc/EvoluCraft-Issues#324]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

maxjerbis

### Pseudo discord

maxjerbis

### Que s'est-il passé ?

avec le nouveau système de vote quand on vote on reçois un mess dans le chat mais il manque un "s" à votes

### Étapes à suivre pour reproduire le bug

voter et voir le message en jeu  

### Qu'aurait-il dû arriver ?

que se sois écrit votes avec un "s"

### Date et heure de la production du bug

23/10/2023 à 20h30

### Serveur

Spawn

### Screen / vidéo

![image](https://github.com/RivrsMc/EvoluCraft-Issues/assets/137526378/a6d06715-08d3-467e-a2c3-c13f5929a0f8)

### Information supplémentaire

X

**Comment by Alexis700** [comment]
ça dépend si tu les récupères une par une ou pas, si tu en récupères plusieurs oui il y aura une faute mais pas une par une, donc on va laisser comme ça
