### ISSUE TITLE
[BUG]quête halloween

### ISSUE THREAD

**Issue by maxjerbis** [RivrsMc/EvoluCraft-Issues#325]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

maxjerbis

### Pseudo discord

maxjerbis

### Que s'est-il passé ?

J'avais une quête que j'ai fini donc j'ai gagné 2k5 puis à 21h elle c'est renouvelé du coup et quand je l'est fini j'ai aussi eu 2k5

### Étapes à suivre pour reproduire le bug

finir une quête halloween

### Qu'aurait-il dû arriver ?

J'aurais du gagner 5k de bonbons

### Date et heure de la production du bug

23/10/2023 à 20h30

### Serveur

Spawn

### Screen / vidéo

![image](https://github.com/RivrsMc/EvoluCraft-Issues/assets/137526378/73bbf473-c872-48fc-a6ac-0dfeb0e1ff78)

### Information supplémentaire

X

**Comment by Asherate** [comment]
Si jamais tu peux faire un ticket pour demander un remboursement, normalement ça à été fix ce matin à 9h.

**Comment by maxjerbis** [comment]
pas besoin de remboursement tkt, merci beaucoup !
