### ISSUE TITLE
[BUG]pets bat-souris sanguinaire

### ISSUE THREAD

**Issue by maxjerbis** [RivrsMc/EvoluCraft-Issues#326]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

maxjerbis

### Pseudo discord

maxjerbis

### Que s'est-il passé ?

le lore du pets bat-souris achetable dans le boutique bonbons via la commande /halloween n'a pas le bon lore quand on l'achète, dans le menu c'est son bon lore mais pas quand on l'achète

### Étapes à suivre pour reproduire le bug

faire /halloween et acheter le pets bat-souris sanguinaire

### Qu'aurait-il dû arriver ?

IL y aurais du avoir le meme lore que dans le menu des achat via les bonbons

### Date et heure de la production du bug

25/10/23 à 18h

### Serveur

Spawn

### Screen / vidéo

![image](https://github.com/RivrsMc/EvoluCraft-Issues/assets/137526378/5e1ff2b8-7251-4f50-ab40-aa7b31dc8430)
![image](https://github.com/RivrsMc/EvoluCraft-Issues/assets/137526378/e384e3d1-1f94-492c-8dad-a4c5a3f7085c)

### Information supplémentaire

X

**Comment by Alexis700** [comment]
Fin de maj
