### ISSUE TITLE
[BUG] /forgeron item ultime

### ISSUE THREAD

**Issue by CardiLyce** [RivrsMc/EvoluCraft-Issues#328]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

CardiLyce

### Pseudo discord

CardiLyce

### Que s'est-il passé ?

C'est affiché qu'il faut 25 niveaux, mais au moment du /forgeron des items ultimes, ça indique que toutes les prérequis ne sont pas respectés
Il faut 30 levels pour les réparer

### Étapes à suivre pour reproduire le bug

1. Item ultime (tout les items évolutives, attention!-
2. /forgeron
3. Réparer son épée ou pioche ultime, et voir le message en rouge qui dit qu'il n'y a pas les prérequis et faut être niveau 30 et non 25

### Qu'aurait-il dû arriver ?

Avoir affiché niveau 30 et non 25

### Date et heure de la production du bug

14h20

### Serveur

Spawn

### Screen / vidéo

![image](https://github.com/RivrsMc/EvoluCraft-Issues/assets/137453062/31148111-48f4-4488-ab24-fa0c86129c5f)

### Information supplémentaire

C'est tout les outils ultimes!

**Comment by Alexis700** [comment]
Je n'ai pas d'erreur, ça a dû être corrigé
