### ISSUE TITLE
[BUG] Synchroniser le plugin des mariages spawn - construction

### ISSUE THREAD

**Issue by CardiLyce** [RivrsMc/EvoluCraft-Issues#330]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

CardiLyce

### Pseudo discord

CardiLyce

### Que s'est-il passé ?

Le plugin mariage n'est pas très bien synchronisé. On peut se marier a plusieurs personnes.

### Étapes à suivre pour reproduire le bug

1. Se marier avec quelqu'un au spawn
2. Aller en constru et voir que les 2 joueurs ne sont pas mariés, ducoup on peut se marier avec un autre joueur en constru01
3. SI trop bug : On peut se remarier avec un 3e joueur en constru02

### Qu'aurait-il dû arriver ?

Ne pas pouvoir se marier avec plusieurs personnes

### Date et heure de la production du bug

Depuis toujours

### Serveur

Spawn

### Screen / vidéo

X

**Comment by Alexis700** [comment]
On ne pourra rien faire, ce n'est pas notre plugin
