### ISSUE TITLE
[BUG] Pack de décoration Halloween 

### ISSUE THREAD

**Issue by Nymeliaa** [RivrsMc/EvoluCraft-Issues#331]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

Nymeliaa

### Pseudo discord

Nymeliaa la bgg

### Que s'est-il passé ?

1- Les packs de décoration d'halloween s'ouvrent en pack de 21. Je m'explique : 

Si on a plusieurs pack dans son inventaire et qu'on en ouvre un, les 20 autres sont ouverts également, mais ne sont pas donnés !

2- Lorsqu'on veut vendre un pack via un shop (coffre de vente) en faisant click gauche, le pack s'ouvre et il est impossible de le vendre. Qu'on fasse click droit ou click gauche, le pack s'ouvre, il faudrait empêcher l'ouverture du pack avec click gauche !

### Étapes à suivre pour reproduire le bug

1- Avoir plusieurs pack de déco dans son inventaire
2- En ouvrir UN
3- Constater que tous les autres ont disparu et qu'on a que les décos d'un pack
4- Pleurer 

1- Avoir un pack de déco
2- Tenter de le vendre en quick shop
3- Faire click gauche avec sur le coffre
4- Constater que le pack s'ouvre
5- Pleurer encore

### Qu'aurait-il dû arriver ?

1- Les packs devraient s'ouvrir UN à UN
2- Les packs ne devraient s'ouvrir qu'avec le click droit

### Date et heure de la production du bug

Depuis le début de la maj Halloween

### Serveur

Spawn

### Screen / vidéo

VIDEO EN EXEMPLE : https://streamable.com/7o5om1

**Comment by Alexis700** [comment]
Le pack existe plus
