### ISSUE TITLE
[SUGGESTION] Agrandir la map Constru01 et Constru02

### ISSUE THREAD

**Issue by CardiLyce** [RivrsMc/EvoluCraft-Issues#332]
### Pseudo en jeu

CardiLyce

### Suggestion

Beaucoup de joueurs/nouveaux joueurs se plaignent que c'est claim partout et que cela devient impossible de trouver une place.

### Décrivez la solution que vous souhaitez

Passer la worldborder de 10k a 12k500 ou quelque chose dans le genre (ça rajouterait 5000 blocks de plus)

**Comment by CardiLyce** [comment]
Par conséquent, quand les nouveaux joueurs arrivent pour la première fois sur la map constru, c'est que le tp random amène le joueur a au moins 5000 blocks du 0 0

**Comment by Alexis700** [comment]
ça ne sera pas fait, hésitez pas à virer les villes inactives
