### ISSUE TITLE
[BUG]canne à pêche émeraude

### ISSUE THREAD

**Issue by maxjerbis** [RivrsMc/EvoluCraft-Issues#333]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

maxjerbis

### Pseudo discord

maxjerbis

### Que s'est-il passé ?

Avec une canne à pêche en émeraude on peut tourner les tableaux dans les autres villes 

### Étapes à suivre pour reproduire le bug

Avoir une canne à pêche en émeraude et faire clique droit sur des tableau dans d'autres villes (pas trust)

### Qu'aurait-il dû arriver ?

qu'on ne puisse pas tourner les tableaux 

### Date et heure de la production du bug

le 30/10/23 à 17h15

### Serveur

Spawn

### Screen / vidéo

https://streamable.com/07cpiu

**Comment by Alexis700** [comment]
On a pas trouvé pourquoi, ça doit être le cas pour toutes les cannes à pêche mais ça vient pas de nous on ne pourra rien y faire
