### ISSUE TITLE
[BUG] Message pour les items expirés de l'HDV

### ISSUE THREAD

**Issue by Nymeliaa** [RivrsMc/EvoluCraft-Issues#336]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

Nymeliaa

### Pseudo discord

Nymeliaa la plus drôle

### Que s'est-il passé ?

Lorsqu'un item à l'HDV est expiré, le joueur reçoit comme message "Vous avez vendu XXX pour XXX" (en gros le message d'achat) Cela perturbe les joueurs qui viennent faire des tickets pour dire qu'ils n'ont pas eu l'argent de la vente. Nous sommes obligés de leur expliquer que l'item est expiré et qu'ils peuvent le récupérer dans l'hdv. 

### Étapes à suivre pour reproduire le bug

1- Avoir un item expiré à l'hdv
2- Etre connecté et constater qu'on reçoit un msg nous disant que l'item a été vendu
3- Ne pas comprendre
4- Pleurer

### Qu'aurait-il dû arriver ?

Il faudrait changer la phrase et mettre que l'item est expiré et que le joueur peut le retrouver dans son /ah > Objets à récupérer 

### Date et heure de la production du bug

Depuis 1875, sur tous les serveurs

### Serveur

Spawn

**Comment by Volrod678** [comment]
Tu pleure beaucoup toi ? 👀

Je vais voir avec le développeur concerné pour qu'il fix ça
