### ISSUE TITLE
[BUG] Supprimer le /pokedex

### ISSUE THREAD

**Issue by CardiLyce** [RivrsMc/EvoluCraft-Issues#337]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

CardiLyce

### Pseudo discord

CardiLyce

### Que s'est-il passé ?

Pas a jour + /pets list est constamment a jour = meilleur

### Étapes à suivre pour reproduire le bug

1. Aucune

### Qu'aurait-il dû arriver ?

Supprimer /pokedex

### Date et heure de la production du bug

13h00

### Serveur

Spawn

**Comment by Alexis700** [comment]
Les joueurs ne sont pas obligé d'utiliser la commande
