### ISSUE TITLE
[BUG] block de stone dans le /pets list

### ISSUE THREAD

**Issue by CardiLyce** [RivrsMc/EvoluCraft-Issues#338]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

CardiLyce

### Pseudo discord

CardiLyce

### Que s'est-il passé ?

Il y a un block de stone tout en haut tout a gauche du /pets list dans les 2 constructions et les 2 ressources

### Étapes à suivre pour reproduire le bug

1. /pets list

### Qu'aurait-il dû arriver ?

Ne pas l'avoir

### Date et heure de la production du bug

16h00

### Serveur

Construction01 (Sarys)

### Screen / vidéo

![image](https://github.com/RivrsMc/EvoluCraft-Issues/assets/137453062/a46b9f83-6d1a-4927-90f2-0eed5e1d95e9)

### Information supplémentaire

En construction01, constrution02, ressource01, ressource02

**Comment by Alexis700** [comment]
C'est le bloque qui permet de changer de page
