### ISSUE TITLE
[BUG] Le goat est bugué !!!

### ISSUE THREAD

**Issue by CardiLyce** [RivrsMc/EvoluCraft-Issues#341]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

CardiLyce

### Pseudo discord

CardiLyce

### Que s'est-il passé ?

Il faut le monter niveau 20 pour que le +35% soit appliqué, alors que dans son lore c'est niveau 5

### Étapes à suivre pour reproduire le bug

1. Niveau 5
2. voir que le +35% n'est pas appliqué

### Qu'aurait-il dû arriver ?

Avoir le +35%

### Date et heure de la production du bug

16h00

### Serveur

Spawn

### Screen / vidéo

![image](https://github.com/RivrsMc/EvoluCraft-Issues/assets/137453062/d838a9c8-22ea-49bf-9760-1749d989ccb0)

**Comment by Volrod678** [comment]
Erreur de lore, fix en dev bientôt fix en prod :)
