### ISSUE TITLE
[BUG] Olaf

### ISSUE THREAD

**Issue by CorieTutTut** [RivrsMc/EvoluCraft-Issues#342]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

Corie__

### Pseudo discord

tuttut_corie

### Que s'est-il passé ?

On peut mettre de la glace si on a frost walker sur des bottes et si on a Olaf de mis, que ce soit dans des claims (trust ou pas trust) et dans les zones sauvages

### Étapes à suivre pour reproduire le bug

1- aller sur constru1/2
2- équiper des bottes frostwalker 
3- équiper Olaf
4- marcher sur l'eau
5- de la glace apparait :( 

### Qu'aurait-il dû arriver ?

1- aller sur constru1/2
2- équiper des bottes frostwalker 
3- équiper Olaf
4- marcher sur l'eau
5- de la glace n'apparait pas :D

### Date et heure de la production du bug

xx xxxx xxxxx 

### Serveur

Construction01 (Sarys)

### Screen / vidéo

https://github.com/RivrsMc/EvoluCraft-Issues/assets/137453358/6808f5a6-978d-4121-8a6b-82ed4bbe8593

### Information supplémentaire

Petite suggestion : retirer l'effet du pet et mettre de l'argent à la place?

**Comment by Alexis700** [comment]
On peut pas y faire grand chose, les joueurs pourront toujours le faire avec frost walker
