### ISSUE TITLE
[BUG]bug visuel avec pets fly

### ISSUE THREAD

**Issue by maxjerbis** [RivrsMc/EvoluCraft-Issues#345]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

maxjerbis

### Pseudo discord

maxjerbis

### Que s'est-il passé ?

quand nous utilisons un pets fly que l'on monte dessus et que l'on se mette sur un escalier nous pouvons voir à travers les blocks

### Étapes à suivre pour reproduire le bug

avoir un pets fly
installer un escalier 
monter sur le pets 
monter le pet sur l'escalier

### Qu'aurait-il dû arriver ?

que nous puissions pas voir à travers les blocks si possible 

### Date et heure de la production du bug

all

### Serveur

Spawn

### Screen / vidéo

![image](https://github.com/RivrsMc/EvoluCraft-Issues/assets/137526378/0150eed9-58c4-4fd6-a2ef-b0f9d974ef98)

### Information supplémentaire

X

**Comment by Alexis700** [comment]
On ne pourra rien faire c'est minecraft qui est fait comme ça
