### ISSUE TITLE
[BUG]Armure Archéologue Enchantable

### ISSUE THREAD

**Issue by ldyie** [RivrsMc/EvoluCraft-Issues#348]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

Ldyie

### Pseudo discord

Idyie

### Que s'est-il passé ?

L'armure Archéologue est enchantable, plus précisément avec des livres d'enchantements,
Par exemples : - Aqua Affinity sur le Casque Archéologue
                        -Mending sur les Bottes Archéologue

### Étapes à suivre pour reproduire le bug

Enchanter une armure Archéologue dans une enclume, avec un livre enchanté

### Qu'aurait-il dû arriver ?

L'armure Archéologue n'est pas sensé avoir des enchantements supplémentaires.

### Date et heure de la production du bug

30/11/2023 à 12h00

### Serveur

Spawn

### Screen / vidéo

![bug 1](https://github.com/RivrsMc/EvoluCraft-Issues/assets/143371203/15645cc5-1393-4c38-97d0-9506b505a84f)

![bug 1 screen 2](https://github.com/RivrsMc/EvoluCraft-Issues/assets/143371203/9231daa5-2ed6-47de-a66f-a3c2c1a919e3)

![bug 1 screen 3](https://github.com/RivrsMc/EvoluCraft-Issues/assets/143371203/87546494-9a01-4baa-a834-67facecb73aa)

![bug 1 screen 4](https://github.com/RivrsMc/EvoluCraft-Issues/assets/143371203/a7173677-724d-4daa-a8c4-752cbcd9e8ab)

![bug 1 screen 5](https://github.com/RivrsMc/EvoluCraft-Issues/assets/143371203/a6c0dd0d-32de-491e-b4a6-d67f7ecb1980)

![bug 1 screen 6](https://github.com/RivrsMc/EvoluCraft-Issues/assets/143371203/f300bb74-7f6c-471c-a161-25da114438e7)

![bug 1 screen 7](https://github.com/RivrsMc/EvoluCraft-Issues/assets/143371203/e30ef96e-5b26-4b11-bc91-7407875ac4e3)

![bug 1 screen 8](https://github.com/RivrsMc/EvoluCraft-Issues/assets/143371203/4e008687-0681-4c73-8357-7c3105e3725e)

### Information supplémentaire

Probablement possible dans chaque monde

**Comment by Alexis700** [comment]
ça donne un petit bonus à l'armure c'est pas très grave, le problème si on change ça, on devra changer toutes les armures in game, des joueurs les cacheront etc etc, autant laisser ça comme ça, c'est un petit bonus
