### ISSUE TITLE
[BUG] Archéologie non-fonctionelle en ressources

### ISSUE THREAD

**Issue by xJuebo** [RivrsMc/EvoluCraft-Issues#349]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

Juebowo

### Pseudo discord

juebowo

### Que s'est-il passé ?

Le pinceau et le marteau d'archéologie ne fonctionnent pas dans les mondes ressources 1 et ressources 2.

### Étapes à suivre pour reproduire le bug

1. Prendre un marteau/brosse d'archéologie. 
2. Cliquer sur le bloc adapté
3. Constater que rien ne se passe

### Qu'aurait-il dû arriver ?

Lorsque l'on clique avec une brosse d'archéologie sur du sable/sable rouge/gravier/argile on est censé pouvoir le casser et obtenir des objets. 

Lorsque l'on clique avec un marteau d'archéologie sur du andesite/granite/diorite/tuff/Spéléothèmes on est censé pouvoir le casser et obtenir des objets. 

### Date et heure de la production du bug

Depuis 5 jours.

### Serveur

Ressource01

### Information supplémentaire

Ce report est valable pour le ressources 1 et le ressources 2.

**Comment by Alexis700** [comment]
Corrigé
