### ISSUE TITLE
[BUG] Yeti mauvais lore

### ISSUE THREAD

**Issue by CardiLyce** [RivrsMc/EvoluCraft-Issues#350]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

CardiLyce

### Pseudo discord

CardiLyce

### Que s'est-il passé ?

Le pet donne +32% Guerrier et non +32% Archimage

### Étapes à suivre pour reproduire le bug

1. L'équiper
2. /jobs bonus Guerrier
3. on voit bien le +32%

### Qu'aurait-il dû arriver ?

Ce serait bien de mettre +32% archimage ou alors corriger la faute dans archimage

### Date et heure de la production du bug

ce matin, 10h30

### Serveur

Construction01 (Sarys)

### Screen / vidéo

![yeti soucis lore](https://github.com/RivrsMc/EvoluCraft-Issues/assets/137453062/15863f8d-2a0e-48c3-8aea-c8011c6d606f)

### Information supplémentaire

Bug réalisable dans tout les mondes

**Comment by Alexis700** [comment]
Corrigé
