### ISSUE TITLE
[BUG] Recycleur du ./noel

### ISSUE THREAD

**Issue by Zerainy** [RivrsMc/EvoluCraft-Issues#353]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

Zerainy

### Pseudo discord

Zerainy

### Que s'est-il passé ?

Il est écrit que le recycleur reprends les items de la box contre des sucres d'orges mais au final il les échanges contre de la monnaie

### Étapes à suivre pour reproduire le bug

échanger un item au recycleur

### Qu'aurait-il dû arriver ?

obtenir des sucres d'orges

### Date et heure de la production du bug

en continue

### Serveur

Spawn

**Comment by Zerainy** [comment]
> Tu as vu ça dans quel menu ?

Dans le menu du pnj recycleur au .monde ./noel

**Comment by Alexis700** [comment]
Tu peux me le screen, car je suis dans le pnj recycleur et je ne vois pas d'erreur
