### ISSUE TITLE
[BUG] Problème avec l'xp bûcheron que donne la hache ultime.

### ISSUE THREAD

**Issue by xJuebo** [RivrsMc/EvoluCraft-Issues#354]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

Juebowo

### Pseudo discord

juebo

### Que s'est-il passé ?

Concrètement, lorsque l'on casse un arbre avec une hache ultime sur les serveur construction 1 et 2. L'xp que l'on récupère est uniquement celui de la bûche que l'on casse avec la hache ultime.

### Étapes à suivre pour reproduire le bug

1. Aller sur un serveur construction (Jaya ou Sarys)
2. Casser un arbre quelconque
3. Constater l'xp que l'on gagne

### Qu'aurait-il dû arriver ?

L'xp gagné devrait être l'xp de toute la hauteur de bûche cassé.

### Date et heure de la production du bug

22/12/23

### Serveur

Construction01 (Sarys)

### Screen / vidéo

![Capture d’écran 2023-12-22 210344](https://github.com/RivrsMc/EvoluCraft-Issues/assets/144448811/0cbd65e2-2d0f-4920-a07e-a5353cefc0e9)

### Information supplémentaire

Bug actif uniquement sur le Jaya et le Sarys.
Sur les mondes ressources, tout est fonctionnel.

**Comment by Alexis700** [comment]
Corrigé
