### ISSUE TITLE
[BUG] texture canne à pêche rubis  (dans la caisse)

### ISSUE THREAD

**Issue by CorieTutTut** [RivrsMc/EvoluCraft-Issues#355]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

Corie__

### Pseudo discord

tuttut_corie

### Que s'est-il passé ?

Il y a la texture d'une canne à pêche normale pour la canne à pêche rubis, dans la caisse rubis

### Étapes à suivre pour reproduire le bug

1- aller au spawn
2- cliquer sur la caisse rubis
3- voir la canne à pêche avec une mauvaise texture

### Qu'aurait-il dû arriver ?

1- aller au spawn
2- cliquer sur la caisse rubis
3- voir la canne à pêche avec la bonne texture

### Date et heure de la production du bug

xxxxxx

### Serveur

Spawn

### Screen / vidéo

![image](https://github.com/RivrsMc/EvoluCraft-Issues/assets/137453358/13fb8aa3-0008-4b02-ade3-136da3d10141)

**Comment by Alexis700** [comment]
C'est good pour moi ne jeu
