### ISSUE TITLE
[BUG] Son de l'augmentation de level du pets GRINCH 

### ISSUE THREAD

**Issue by CorieTutTut** [RivrsMc/EvoluCraft-Issues#356]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

Corie__

### Pseudo discord

tuttut_corie

### Que s'est-il passé ?

Lorsque l'on level up le pets Grinch, on n'entend pas le bon son. 
-> son de l'xp vanilla et non le son du level up de pets

### Étapes à suivre pour reproduire le bug

1- faire spawn Grinch
2- faire level up avec des bonbons
3- entendre le mauvais son

### Qu'aurait-il dû arriver ?

1- faire spawn Grinch
2- faire level up avec des bonbons
3- entendre le bon son

### Date et heure de la production du bug

depuis la maj nowel

### Serveur

Spawn

### Screen / vidéo

https://github.com/RivrsMc/EvoluCraft-Issues/assets/137453358/45c46bc4-d520-4919-8273-c9ad39ae9411

**Comment by Alexis700** [comment]
Corrigé (Plusieurs pets avaient se problème)
