### ISSUE TITLE
[BUG] /forgeron sur l'épée ultime 

### ISSUE THREAD

**Issue by CorieTutTut** [RivrsMc/EvoluCraft-Issues#359]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

Corie__

### Pseudo discord

tuttut_corie

### Que s'est-il passé ?

Quand on veut /forgeron l'épée ultime, nous devons **impérativement** avoir 30 levels sur nous. Quand on /forgeron par la suite, on nous retire bel et bien 25 levels et non 30

### Étapes à suivre pour reproduire le bug

1- avoir 25 levels
2- vouloir /forgeron
3- ne pas pouvoir car nous n'avons pas les pré-réquis
4- avoir 30 levels (pas 26, ni 27, ni 28, ni 29)
5- vouloir /forgeron
6- pouvoir la réparer MAIS quand même avoir les 5 levels de différences 

### Qu'aurait-il dû arriver ?

1- avoir 25 levels
2- vouloir /forgeron
3- pouvoir

### Date et heure de la production du bug

xx xxxx xxxxx 

### Serveur

Spawn

### Screen / vidéo

**Vidéo level 25 :** 

https://github.com/RivrsMc/EvoluCraft-Issues/assets/137453358/81b5dad5-8973-4c9d-a905-916f7a4d9ace

**Vidéo level 30 :** 

https://github.com/RivrsMc/EvoluCraft-Issues/assets/137453358/60a66aed-51c2-4101-84bd-bc3a495328df

On voit bien qu'il nous reste 5 levels après le /forgeron

**Comment by CorieTutTut** [comment]
il semblerait que ça soit la même chose sur tous les items ultimes*

**Comment by CardiLyce** [comment]
un autre issue était sur la même problématique y a quelques mois, mais aucun fix n'était présent https://github.com/RivrsMc/EvoluCraft-Issues/issues/328

**Comment by Alexis700** [comment]
Corrigé
