### ISSUE TITLE
[BUG] avoir le pet dracon, on peut aller jusqu'en -6000 (Y) dans l'end 

### ISSUE THREAD

**Issue by CorieTutTut** [RivrsMc/EvoluCraft-Issues#360]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

Corie__

### Pseudo discord

tuttut_corie

### Que s'est-il passé ?

Je ne sais pas si vous pouvez y faire quelque chose, mais c'est le report d'un joueur 
Quand on va sur le dracon dans l'end et qu'on va dans le vide, le pets va jusqu'en -65 et faut le déséquiper pour aller plus bas (voir la vidéo) 

### Étapes à suivre pour reproduire le bug

1- aller sur le dracon
2- aller dans le vide
3- jusqu'en -65 on est sur le dracon
4- déséquiper le dracon
5- être dans le vide
6- pouvoir descendre jusqu'en -6000

### Qu'aurait-il dû arriver ?

1- aller sur le dracon
2- aller dans le vide
3- être limité ? 

### Date et heure de la production du bug

xxxxxx

### Serveur

Ressource01

### Screen / vidéo

https://streamable.com/67ctvk

**Comment by Alexis700** [comment]
ça ne sera pas corrigé, si des joueurs s'amusent à faire ça bah, tant mieux pour eux
