### ISSUE TITLE
[BUG] force avec le dracon volcanique

### ISSUE THREAD

**Issue by CorieTutTut** [RivrsMc/EvoluCraft-Issues#361]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

Corie__

### Pseudo discord

tuttut_corie

### Que s'est-il passé ?

Report d'un joueur : 
"Je vais illustrer l'exemple par mon cas
J'ai le dracon Volcanique et épée diablotin
Je prends la lame diablotin j'ai toujours Force II
Je prends autre chose, l'effet Force disparait
Reprendre l'épée diablotin donne alors Force I 
Je dois donc déséquiper puis rééquiper le volcanique pour avoir force II"

### Étapes à suivre pour reproduire le bug

1- équiper le dracon volcanique **force II**
2- avoir une lame du diablotin et l'avoir en main **force II**
3- prendre une autre épée random en main 
4- perdre l'effet de force (du dracon)
5- reprendre la lame du diablotin **perdre l'effet force II du pets volcanique**

### Qu'aurait-il dû arriver ?

1- équiper le dracon volcanique **force II**
2- avoir une lame du diablotin et l'avoir en main **force II**
3- prendre une autre épée random en main 
4- ne pas perdre l'effet de force (du dracon)
5- reprendre la lame du diablotin **perdre l'effet force II du pets volcanique**

### Date et heure de la production du bug

xx xxxx xxxxx 

### Serveur

Spawn

### Screen / vidéo

https://streamable.com/evbj8m

**Comment by ArDiDEx** [comment]
Hello
fix au prochain restart
merci du report
