### ISSUE TITLE
[BUG] Epée Rubis

### ISSUE THREAD

**Issue by Nymeliaa** [RivrsMc/EvoluCraft-Issues#364]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

Nym

### Pseudo discord

Nym

### Que s'est-il passé ?

L'épée rubis, qui fait de base du 20% de vitesse, va aussi vite que la pirate qui fait du 40% de vitesse

### Étapes à suivre pour reproduire le bug

1- Taper avec l'épée

### Qu'aurait-il dû arriver ?

L'épée rubis ne devrait pas aller aussi vite

### Date et heure de la production du bug

Depuis 1785

### Serveur

Spawn

**Comment by Alexis700** [comment]
Corrigé
