### ISSUE TITLE
[BUG] ASE en anglais sur Jaya 

### ISSUE THREAD

**Issue by CorieTutTut** [RivrsMc/EvoluCraft-Issues#365]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

Corie__

### Pseudo discord

tuttut_corie

### Que s'est-il passé ?

L'ase est bien en français sur le constru 1 (Sarys), mais reste toujours en anglais sur le constru 2 (jaya) 

### Étapes à suivre pour reproduire le bug

x

### Qu'aurait-il dû arriver ?

x

### Date et heure de la production du bug

xx xxxx xxxxx 

### Serveur

Construction02 (Jaya)

### Screen / vidéo

Sarys / constru 1 : 
![image](https://github.com/RivrsMc/EvoluCraft-Issues/assets/137453358/e44a9da4-ea82-4502-8a80-77e7f6979308)

Jaya / constru 2 : 

![image](https://github.com/RivrsMc/EvoluCraft-Issues/assets/137453358/ca3886a5-5130-4bff-b875-04dfcdf81b76)

### Information supplémentaire

x

**Comment by mrsxnshxne** [comment]
C'est corrigé
