### ISSUE TITLE
[SUGGESTION] rajouter qu'il est possible d'obtenir des shulkers shell en votant /aventurier -> info

### ISSUE THREAD

**Issue by CorieTutTut** [RivrsMc/EvoluCraft-Issues#366]
### Pseudo en jeu

Corie__

### Suggestion

![image](https://github.com/RivrsMc/EvoluCraft-Issues/assets/137453358/96e3dde4-2454-4150-9947-4c2934317118)

Rajouter que c'est possible de l'obtenir en votant

### Décrivez la solution que vous souhaitez

Rajouter que c'est possible de l'obtenir en votant

**Comment by Alexis700** [comment]
Corrigé
