### ISSUE TITLE
[BUG] Casque d'ares sans effet

### ISSUE THREAD

**Issue by CardiLyce** [RivrsMc/EvoluCraft-Issues#367]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

CardiLyce

### Pseudo discord

CardiLyce

### Que s'est-il passé ?

Le casque d'Ares ne donne pas l'effet Night vision

### Étapes à suivre pour reproduire le bug

1. Équiper le casque
2. Aucun effet

### Qu'aurait-il dû arriver ?

Avoir l'effet de Night Vision

### Date et heure de la production du bug

23h40

### Serveur

Construction02 (Jaya)

### Screen / vidéo

![2024-01-05_23 43 53](https://github.com/RivrsMc/EvoluCraft-Issues/assets/137453062/6d1c95cf-c408-472a-b518-a88658b1566b)

### Information supplémentaire

Ne fonctionne dans aucun monde

**Comment by Alexis700** [comment]
Il marche mais il faut l'équiper depuis sa hotbar
