### ISSUE TITLE
[BUG]effet pets roi de la glisse

### ISSUE THREAD

**Issue by maxjerbis** [RivrsMc/EvoluCraft-Issues#369]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

maxjerbis

### Pseudo discord

maxjerbis

### Que s'est-il passé ?

Le pets Roi de la glisse qui affiche + 25% dans le métier de fermier ne donne que + 15% de bonus dans le métier de fermier.

### Étapes à suivre pour reproduire le bug

Avoir un pets roi de la glisse le mettre dans son /pets l'activer et faire /jobs bonus fermier 

### Qu'aurait-il dû arriver ?

Qui sois écrit sur le pets + 15% de bonus fermier ou alors qu'il boost en effet dans le /jobs bonus fermier + 25 % comme ce qui est écrit actuellement.

### Date et heure de la production du bug

10/01/2024 à 21h43

### Serveur

Spawn

### Screen / vidéo

![image](https://github.com/RivrsMc/EvoluCraft-Issues/assets/137526378/ccf94c66-53ce-4c58-82a3-62ff5e48319d)
![image](https://github.com/RivrsMc/EvoluCraft-Issues/assets/137526378/5eac782d-b1d4-4c56-8208-533bf874fff3)

### Information supplémentaire

X

**Comment by Alexis700** [comment]
Corrigé, et d'ailleurs il ne donnait même pas 15% mais 0%

**Comment by maxjerbis** [comment]
super, merci ! 
Si des fois il donnait bien les +15% mais ça ne fonctionnait pas tout le temps.
Bas tu vois bien, sur mon screen j'avais que le roi de la glisse sans aucun autres pets ni armure.
