### ISSUE TITLE
[BUG]Minerais mine public

### ISSUE THREAD

**Issue by maxjerbis** [RivrsMc/EvoluCraft-Issues#370]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

maxjerbis

### Pseudo discord

maxjerbis

### Que s'est-il passé ?

Nous ne pouvons pas casser les minerais de diamant dans la mine public

### Étapes à suivre pour reproduire le bug

Miner les minerais de diamant 

### Qu'aurait-il dû arriver ?

Que l'on drope les minerais

### Date et heure de la production du bug

18/01/24

### Serveur

Spawn

### Screen / vidéo

X

### Information supplémentaire

X

**Comment by Alexis700** [comment]
Corrigé
