### ISSUE TITLE
[BUG]/quêtes

### ISSUE THREAD

**Issue by maxjerbis** [RivrsMc/EvoluCraft-Issues#372]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

maxjerbis

### Pseudo discord

maxjerbis

### Que s'est-il passé ?

Dans l'interface du /quête dans "récompenses des quêtes, dans légendaires il est écrit 2 balises or c'est 3

### Étapes à suivre pour reproduire le bug

faire /quêtes -> quêtes -> récompenses quêtes -> aller jusqu'à légendaire

### Qu'aurait-il dû arriver ?

Que se soit écrit 3 balises

### Date et heure de la production du bug

le 09/02/04 à 18h18

### Serveur

Spawn

### Screen / vidéo

![image](https://github.com/RivrsMc/EvoluCraft-Issues/assets/137526378/334fdbef-e0a8-4d77-91f3-8f19e8178e9d)

### Information supplémentaire

X

**Comment by mrsxnshxne** [comment]
C'est corrigé
