### ISSUE TITLE
[BUG]Ailes-Ange

### ISSUE THREAD

**Issue by maxjerbis** [RivrsMc/EvoluCraft-Issues#374]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

maxjerbis

### Pseudo discord

maxjerbis

### Que s'est-il passé ?

Les ailes du paque ange ne sont pas bien mise, elle sont trop haute 

### Étapes à suivre pour reproduire le bug

avoir le paque ange

### Qu'aurait-il dû arriver ?

Qu'elle soir à la bonne hauteur

### Date et heure de la production du bug

le 09/02/04 à 18h25

### Serveur

Spawn

### Screen / vidéo

![image](https://github.com/RivrsMc/EvoluCraft-Issues/assets/137526378/b9952248-f47a-4549-9b24-77a91d688759)

**Comment by mrsxnshxne** [comment]
C'est corrigé
