### ISSUE TITLE
[BUG]lore pets citrouillarde translucide

### ISSUE THREAD

**Issue by maxjerbis** [RivrsMc/EvoluCraft-Issues#376]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

maxjerbis

### Pseudo discord

maxjerbis

### Que s'est-il passé ?

Le lore du pets citrouillarde translucide n'est pas à jour, il est écrit au niveau 1 : 250 bonbons de l'évent halloween alors que maintenant il est sensé donné des cristaux de l'ombre 

### Étapes à suivre pour reproduire le bug

Avoir le pets citrouillarde translucide et regarder son lore

### Qu'aurait-il dû arriver ?

Que se soir écrit au niveau 1 : 250 avec les signe des crystaux d'ombre

### Date et heure de la production du bug

le 11/02/24 à 20h25

### Serveur

Spawn

### Screen / vidéo

![image](https://github.com/RivrsMc/EvoluCraft-Issues/assets/137526378/5d528374-83ea-4d2b-8f5f-38203484b1d8)

### Information supplémentaire

X

**Comment by mrsxnshxne** [comment]
C'est corrigé
