### ISSUE TITLE
[BUG] Mauvaise description du pack décoration de saint valentin

### ISSUE THREAD

**Issue by Mr-Tomite** [RivrsMc/EvoluCraft-Issues#377]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

Tomite_

### Pseudo discord

Tomite

### Que s'est-il passé ?

Le message lors de l'ouverture du pack de décoration dit que l'on ouvre un pack de Noël

### Étapes à suivre pour reproduire le bug

Ouvrir le pack de décoration

### Qu'aurait-il dû arriver ?

Dire que l'on ouvre le pack de saint valentin

### Date et heure de la production du bug

14/02 à 18h

### Serveur

Spawn

### Screen / vidéo

![image_2024-02-14_180200753](https://github.com/RivrsMc/EvoluCraft-Issues/assets/137481730/0260c024-a76d-4ee2-85a1-10fd728059e4)

**Comment by mrsxnshxne** [comment]
C'est corrigé
