### ISSUE TITLE
[BUG] possibilité de casser des blocs sensé être incassable en mine 

### ISSUE THREAD

**Issue by Otachi0** [RivrsMc/EvoluCraft-Issues#58]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication

### Pseudo en jeu

Otachi_i

### Pseudo discord

otachi_i

### Que s'est-il passé ?

Les joueurs qui minent avec un outil 3x3 dans les warp mine peuvent casser les blocs à côté sensé être incassable 

### Étapes à suivre pour reproduire le bug

aller au wharf mine, et miner un minerais avec une pioche 3x3

### Qu'aurait-il dû arriver ?

seule le minerais miné devrait être casser 

### Date et heure de la production du bug

39/06/20023 21h02

### Serveur

Spawn

### Screen / vidéo

![2023-06-29_20 55 39](https://github.com/RivrsMc/EvoluCraft-Issue/assets/137453478/042a78c2-0a35-4d8f-947f-bd296fdcd540)

**Comment by ArDiDEx** [comment]
Hello! ça sera fix dans les prochains jours
Merci du report
